[theme]
primaryColor = "#ff1a1a"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0f"
textColor = "#e8e0d0"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false
